

export const validationMessages = {
    image: `File is required`,
    name: `Please enter the name.`,
    nameMax: `Name is too long ( Maximum 100 characters )`,
    NoFcopies: `Copies are Required`,
    categories: `Categories are required`,
    price: `Price is required`,
    royalty: `Royalty is required`,
    coverimage: `Cover image is required`,
    descriptionMax: "Description is too long ( Maximum 1000 characters )",
    descriptionLow: "Please enter the description.",
    fName: `Please enter your first name.`,
    lName: `Please enter your last name.`,
    allowAlphabets: `This field allow alphabets only.`,
    emailReq: `Please enter your email address.`,
    validEmail: `Please enter a valid email address.`,
    passwReq: `Please enter your password.`,
    validPass: `Password must include:`,
    cpasswReq: `Please re-enter the password for confirmation.`,
    notMatchPassw: `Passwords must match.`,
    phoneReq: `Please enter your phone number.`,
    validMobile: `Please enter a valid phone number.`,
    reqEnquiryType: "Enquiry type is required.",
    reqQueryMessage: "Message is required.",
    allowMax8: "Allow max 8 characters.",
    allowMax20: "Allow max 20 characters.",
    allowMin2: "Allow min 2 characters.",
    Time_from: "From time is required",
    royality: `Royality should be less Than %s or min 0`,
    otpEnter: "Please enter verification code.",
    validOtp: `Please enter a valid verification code.`,
    invalTime: "Please enter a valid time.",
    sameTime: "To time should be greater than Form time.",
    longBio: `Bio is too long ( Maximum 500 characters )`,
    longUserName: `Username is too long ( Maximum 25 characters )`,
    require: "This field is require.",
    reqTermAndPrivacy:
        "Please agree to the Terms & Conditions , Privacy Policy and Purchase Policy",
    qtyGreaterThan: "Qty should be greater than 0.",
    reqPrice: "Please enter a price for your offer.",
    priceGreaterThan: "Amount should be greater than 0.",
    reqDate: "Please select date.",
};

